### ISSUE TITLE
A few questions/requets

### ISSUE THREAD

**Issue by bstashio** [plentycode/sass-export#17]
Hello,

I have the following questions/requests:

- I need support for Sass syntax (older syntax version).
- I would like to get the `json` output as an `object` instead of an `array`; using keys instead of array indexes makes it easier to read and use.
- It's confusing to have the same key "`mixins`" for both `functions` and `mixins`; please consider assigning keys accordingly in the generated `json` file.
- Is there any callback that I can use to append some additional data to the generated `json` file?  for instance I might want to add the source file path or the file GitHub repository URL.
- It would be great if you could provide the option of naming the output keys as any user sees fit; for example I would like to change the following keys:
  - `globals` -> `variables`
  - `variable` -> `name`
- Currently, if a `mixin` or a `function` doesn't have parentheses it's ignored by the parser;  they shouldn't be ignored as it's perfectly normal to have some of them without parameters and parentheses.

I really like you're approach and I think this package is way better than many others out there; it has all the essential elements to make a very useful one.

Thanks for your efforts

**Comment by civan** [comment]
Hey there,
Great stuff, thanks for the feedback. 
I will check and create separate issues to take a look.

thanks

**Comment by bstashio** [comment]
Sounds great!
