### ISSUE TITLE
Rename "variable" to "name"

### ISSUE THREAD

**Issue by civan** [plentycode/sass-export#20]
Currently in the [exported json](https://raw.githubusercontent.com/plentycode/sass-export/develop/exported-examples/annotations.json) the variable name is called `variable` please rename it to "name"

```json
{
  "fonts": [
        { "variable": "$font-size", "value": "16px", "compiledValue": "16px" },
        { "variable": "$font-color", "value": "$brand-gray-medium", "compiledValue":"#d6d6d6" }
    ]
}
```

We want it to be:
```json
{
  "fonts": [
        { "name": "$font-size", "value": "16px", "compiledValue": "16px" },
        { "name": "$font-color", "value": "$brand-gray-medium", "compiledValue":"#d6d6d6" }
    ]
}
```

Don't forget to update:
- [ ] source code: #31
- [ ] unit tests: #31
- [x] documentation:  #29
- [x] examples: #22, #24, #25, #26, #27, #28

**Comment by chirag-jn** [comment]
I have updated examples and documentation. Where are the unit tests? I am a beginner.

**Comment by civan** [comment]
Hi @chirag-jn,
thanks for helping out, I'm glad to help.
you should find the test file right next to the source file; these files are in the src/ folder. for example
```
 parser.ts
 parser.test.ts
```

let me know if this helps
