### ISSUE TITLE
[HELP] @include relative file

### ISSUE THREAD

**Issue by zacharyrs** [plentycode/sass-export#51]
Hi,

I'm having a little trouble with this.
I have a file in `./src/base/components/css-vars.scss`, which has a few variable definitions.
This file ends with `@import '../../content/css-vars.scss'`, with the goal of including the content of `./src/content/css-vars.scss`.

Unfortunately this doesn't resolve, so I'm not sure if I'm missing something?

**Comment by zacharyrs** [comment]
On a complete sidenote, is map-get not supported by this?

**Comment by civan** [comment]
Hi there,
you need to specify what folder you are importing this files from:

- are you using the CLI? 
then you should use --dependencies flag as shown [here](https://github.com/plentycode/sass-export#include-paths-for-import)

- if you're using in your node app:
 ``` js
var options = {
  inputFiles: ['_variables.scss', '_fonts.scss'],
  includePaths: ['libs/'] // don't forget this is the folder path not the files
};
```
I hope this can help!

**Comment by zacharyrs** [comment]
Hi, I'm using sass-export via node. 

```js
const cssVars = sassExport({
    inputFiles: ['./base/components/css-vars.scss'],
    includePaths: ['./content/'],
}).getStructured()
```

I suspect the issue is due to the import being relative to the parent's parent.

**Comment by zacharyrs** [comment]
Ah I see, that's a little annoying.
I was hoping to merge maps between the two files, as one is generic and the second contains overrides.

Perhaps this isn't the best tool for that?

**Comment by zacharyrs** [comment]
Figured I could close this, as I opted to instead use a sass function to get variables from a js object
