### ISSUE TITLE
Cannot use `map-get` within a map

### ISSUE THREAD

**Issue by DEfusion** [plentycode/sass-export#55]
I'm using maps to configure multiple variables as part of a theming system, and trying to use `map-get` within a map causes errors with sass-export.

Given the following SASS:

```SCSS
$base: (
    foo: 'value'
);

$target: (
    bar: map-get($base, foo)
);
```

You get the following error: 

`Invalid CSS after "...#{map-get($base": expected expression (e.g. 1px, bold), was \'}";}\'`

**Comment by civan** [comment]
Hi @DEfusion thanks for fixing it!

let's publish this new bug fix version, I will let you know.

thanks!
