### ISSUE TITLE
The first underscore in a variable name is replaced by a dash

### ISSUE THREAD

**Issue by ryuran** [plentycode/sass-export#77]
Hello,

We recently change our naming convention to use underscore for our variables and it make appear this issue.

The first underscore in a variable name is replaced by a dash.

Input: 
```scss
 $color_dark_red: #400;
 ```
 
 Output:
 ```json
 {
  "variables": [
    {
      "name": "$color-dark_red",
      "value": "#400",
      "compiledValue": "#400"
    }
  ]
}
```

it can be reproduce on the online tool: https://sass-export.plentycode.com/

**Comment by ryuran** [comment]
I suspect this line of code https://github.com/plentycode/sass-export/blob/master/src/app/parser/parser.ts#L120

**Comment by PlentyCodeDev** [comment]
thanks @ryuran :tada:
